### ISSUE TITLE
Can not access scim api via UMA

### ISSUE THREAD

**Issue by nzinfo** [GluuFederation/SCIM-Client#46]
I'm trying to call scim api via uma. When I following the document https://gluu.org/docs/ce/3.1.1/user-management/scim2/ , some exception raised.

The backtrace said,
```
2017-11-01 13:33:04,782 ERROR [qtp1837543557-14] [org.xdi.oxauth.client.TokenRequest] (TokenRequest.java:343) - null
java.lang.NullPointerException: null
        at org.xdi.oxauth.model.crypto.OxAuthCryptoProvider.sign(OxAuthCryptoProvider.java:161) ~[oxauth-model-3.1.1.Final.jar:?]
        at org.xdi.oxauth.client.TokenRequest.getClientAssertion(TokenRequest.java:338) [oxauth-client-3.1.1.Final.jar:?]
        at org.xdi.oxauth.client.TokenClient.exec(TokenClient.java:265) [oxauth-client-3.1.1.Final.jar:?]
        at org.xdi.oxauth.client.uma.wrapper.UmaClient.request(UmaClient.java:178) [oxauth-client-3.1.1.Final.jar:?]
        at org.xdi.oxauth.client.uma.wrapper.UmaClient.request(UmaClient.java:225) [oxauth-client-3.1.1.Final.jar:?]
        at org.xdi.oxauth.client.uma.wrapper.UmaClient.requestPat(UmaClient.java:37) [oxauth-client-3.1.1.Final.jar:?]
        at org.gluu.oxtrust.service.uma.BaseUmaProtectionService.retrievePatToken(BaseUmaProtectionService.java:96) [classes/:?]
        at org.gluu.oxtrust.service.uma.BaseUmaProtectionService.getPatToken(BaseUmaProtectionService.java:51) [classes/:?]
        at org.gluu.oxtrust.service.uma.ScimUmaProtectionService$Proxy$_$$_WeldSubclass.getPatToken(Unknown Source) [classes/:?]
        at org.gluu.oxtrust.service.uma.BaseUmaProtectionService.isExistPatToken(BaseUmaProtectionService.java:66) [classes/:?]
        at org.gluu.oxtrust.service.uma.ScimUmaProtectionService$Proxy$_$$_WeldSubclass.isExistPatToken(Unknown Source) [classes/:?]
        at org.gluu.oxtrust.service.uma.BaseUmaProtectionService.isEnabledUmaAuthentication(BaseUmaProtectionService.java:61) [classes/:?]
        at org.gluu.oxtrust.service.uma.ScimUmaProtectionService$Proxy$_$$_WeldSubclass.isEnabledUmaAuthentication(Unknown Source) [classes/:?]
        at org.gluu.oxtrust.service.uma.ScimUmaProtectionService.isEnabled(ScimUmaProtectionService.java:62) [classes/:?]
        at org.gluu.oxtrust.service.uma.ScimUmaProtectionService$Proxy$_$$_WeldSubclass.isEnabled$$super(Unknown Source) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor.monitor(InvocationMonitor.java:125) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
        at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:85) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:73) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:57) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.gluu.oxtrust.service.uma.ScimUmaProtectionService$Proxy$_$$_WeldSubclass.isEnabled(Unknown Source) [classes/:?]
        at org.gluu.oxtrust.service.uma.ScimUmaProtectionService$Proxy$_$$_WeldClientProxy.isEnabled(Unknown Source) [classes/:?]
        at org.gluu.oxtrust.ws.rs.scim2.BaseScimWebService.processAuthorization(BaseScimWebService.java:124) [classes/:?]
        at org.gluu.oxtrust.ws.rs.scim2.UserWebService$Proxy$_$$_WeldSubclass.processAuthorization(Unknown Source) [classes/:?]
        at org.gluu.oxtrust.ws.rs.scim2.UserWebService.searchUsers(UserWebService.java:107) [classes/:?]
        at org.gluu.oxtrust.ws.rs.scim2.UserWebService$Proxy$_$$_WeldSubclass.searchUsers$$super(Unknown Source) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]

```
Here's my code,
[App.java.txt](https://github.com/GluuFederation/SCIM-Client/files/1434286/App.java.txt)

I'm using version_3.1.1, but my manage console has a bit different 

![1509543697 1](https://user-images.githubusercontent.com/1139025/32277740-5d534612-bf4e-11e7-
91a7-ba421482754b.png)

My client is following the guide, 
```
Client Name: SCIM-Client. You may enter a different name
Client secret: Think of it as a password. Choose something safe but comfortable for your testing exercise
Application type: Native
Persist Client Authorizations: true
Subject type: pairwise
Authentication method for the Token Endpoint: client_secret_basic
Require Auth Time: false
Logout Session Required: false
Include Claims In ID Token: false
Client Secret Expires: Choose a future date (one week ahead is fine)
```
I don't know what's wrong with my configuration.

**Comment by nzinfo** [comment]
![1509543697 1](https://user-images.githubusercontent.com/1139025/32278096-866fd168-bf4f-11e7-8680-242a96954069.png)

**Comment by willow9886** [comment]
@nzinfo can you please add this as an issue on https://support.gluu.org ? We will evaluate and determine if it is a bug.

**Comment by nynymike** [comment]
Closing this because github is not for support

**Comment by nzinfo** [comment]
I'm quit sure this is a bug. I'm using the latest oxauth & oxtrust. When I visit 
GET /identity/restv1/scim/v2/ServiceProviderConfig 
GET /identity/restv1/scim/v2/ResourceTypes
Response are fine.
But When I visit
GET /identity/restv1/scim/v2/Users
The Response is 
{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"status":"503","scimType":"","detail":"SCIM was disabled"}
I've been turned "Enable Scim" On, and Enable  UMA RPT Policies  =>uma_client_authz_rpt_policy.
I took a look at ScimClient's code base, It depends on  Response.Status.UNAUTHORIZED status code, but  when I visit `/identity/restv1/scim/v2/Users` directly , the respone code is 503, so the authorize process will not start.
I check the log of identity in oxAuth TokenRequest.java:338,  it turned out that sharedKey is null.
So I think, when sharedKey is null, oxAuth should return 403 instead of 503.

I've registed support.gluu.org,  using email limn@coreseek.com , but no active or password-reset mail recieved.

**Comment by willow9886** [comment]
@nzinfo looking into the support registration issue... I see your user created in the database, but marked as inactive. Will update this when I know more. Also, assigning to one of our engineers to check the SCIM/UMA issue.

**Comment by jgomer2001** [comment]
@nzinfo definitely you'd better use [support portal](https://support.gluu.org) to get assistance. The impression I get is that you are kind of mixing the concepts of test mode and UMA for scim protection. 
While you open the ticket, use in your java code an empty string for `umaAatClientId` and ensure the `umaAatClientId` is the right one.
