### ISSUE TITLE
Some tests return an HTTP response 400

### ISSUE THREAD

**Issue by Yamilquery** [GluuFederation/SCIM-Client#72]
I've followed the documentation offered in https://www.gluu.org/docs/ce/user-management/scim2/#protection-using-uma. However I'm getting some errors when I execute the tests.

## Expected behavior

Gluu Server version: 3.1.4

Run the SCIM-Client tests successfully.

## Actual behavior

Of the 109 tests run, 19 tests are failed because they return an HTTP response 400

## Minimized example

This is what I get when I execute ```mvn test```

```shell
➜  SCIM-Client git:(master) ✗ mvn test   
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< gluu.scim.client:scim-client2 >--------------------
[INFO] Building SCIM-Client 4.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ scim-client2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ scim-client2 ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ scim-client2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 35 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ scim-client2 ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ scim-client2 ---
[INFO] Surefire report directory: /Users/yamildiazaguirre/Documents/SCIM-Client/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
16:04:02 INFO  BaseTest.java:44 - Invoked initTestSuite of 'Corner and other weird cases'
16:04:02 INFO  BaseTest.java:72 - Initializing client...
16:04:04 INFO  SchemasTest.java:71 - Found User Schema Extension: GluuUserCustomExtension
16:04:04 DEBUG MinimalUserTest.java:29 - Creating mimimal user from json...
16:04:07 DEBUG UserBaseTest.java:26 - User created with id @!ADF2.014A.3A4E.E27B!0001!DC3E.136B!0000!8636.F81C.F77F.9E59
16:04:07 DEBUG MinimalUserTest.java:37 - Updating user scim_test_bjensen_1 with json
16:04:07 DEBUG MinimalUserTest.java:44 - Updated user Barbara
16:04:07 DEBUG UserBaseTest.java:33 - Deleting user bjensen_1
16:04:07 DEBUG UserBaseTest.java:36 - deleted
16:04:07 DEBUG MinimalGroupTest.java:31 - Creating mimimal group from json...
16:04:07 DEBUG MinimalGroupTest.java:37 - Group created with id @!ADF2.014A.3A4E.E27B!0001!DC3E.136B!0003!7D53.ED5B
16:04:07 DEBUG MinimalGroupTest.java:45 - Updating group scim_test_worldowners with json
16:04:07 DEBUG MinimalGroupTest.java:52 - Updated group scim_test_worldmanagers
16:04:07 DEBUG MinimalGroupTest.java:59 - Deleting group scim_test_worldowners
16:04:08 DEBUG MinimalGroupTest.java:62 - deleted
16:04:08 DEBUG AverageUserTest.java:35 - Creating user from json...
16:04:08 DEBUG UserBaseTest.java:26 - User created with id @!ADF2.014A.3A4E.E27B!0001!DC3E.136B!0000!E7B4.047D.E8B0.F5C9
16:04:08 DEBUG AverageUserTest.java:43 - Updating user scim_test_bjensen_1 with json
16:04:08 DEBUG AverageUserTest.java:56 - Updated user Barbara
16:04:08 DEBUG AverageUserTest.java:73 - Updating user scim_test_bjensen_1
16:04:08 DEBUG AverageUserTest.java:85 - Updated user Barbara
16:04:08 DEBUG AverageUserTest.java:113 - Updated user scim_test_bjensen_1
16:04:08 DEBUG UserBaseTest.java:33 - Deleting user scim_test_bjensen_1
16:04:09 DEBUG UserBaseTest.java:36 - deleted
16:04:09 DEBUG FullUserTest.java:35 - Creating user from json...
16:04:09 DEBUG SimpleSearchUserTest.java:33 - Creating user from json...
16:04:10 DEBUG UserBaseTest.java:26 - User created with id @!ADF2.014A.3A4E.E27B!0001!DC3E.136B!0000!2647.5BB8.A1A8.D414
16:04:10 DEBUG ComplexSearchUserTest.java:68 - Searching at most 3 users using POST verb
16:04:10 DEBUG ComplexSearchUserTest.java:69 - Sorted by family name descending
16:04:10 DEBUG ComplexSearchUserTest.java:70 - Retrieving only the attributes [name.familyName, active]
16:04:10 DEBUG ComplexSearchUserTest.java:140 - Searching at most 3 users using POST verb
16:04:10 DEBUG ComplexSearchUserTest.java:141 - Sorted by displayName ascending
16:04:10 DEBUG ComplexSearchUserTest.java:142 - Excluding the attributes [x509Certificates, entitlements, roles, ims, phoneNumbers, addresses, emails, groups]
16:04:10 DEBUG ComplexSearchUserTest.java:39 - Searching users with attribute nickName existent or ims.value=Skype using POST verb
16:04:11 DEBUG SimpleSearchUserTest.java:61 - Searching user with attribute givenName = Barbara using POST verb
16:04:11 DEBUG SimpleSearchUserTest.java:82 - Searching user with attribute emails.value like gluu.org or phone numbers with type unassigned or value containing '+' using POST verb
16:04:11 DEBUG SimpleSearchUserTest.java:110 - Calculating the total number of users
16:04:12 DEBUG SimpleSearchUserTest.java:119 - There are 3 users!
16:04:12 DEBUG SimpleSearchUserTest.java:42 - Searching user with attribute locale = es_ES and created date >= 2019-02-12T22:04:10.423Z using GET verb
16:04:12 DEBUG UserBaseTest.java:33 - Deleting user scim_test_bjensen_1
16:04:12 DEBUG UserBaseTest.java:36 - deleted
16:04:12 INFO  GroupAssignUserTest.java:40 - Creating 3 users...
16:04:13 INFO  GroupAssignUserTest.java:66 - Assigning users to new group...
16:04:13 INFO  GroupAssignUserTest.java:90 - Creating a secondary group...
16:04:13 INFO  GroupAssignUserTest.java:112 - Issuing query with filter: id eq "@!ADF2.014A.3A4E.E27B!0001!DC3E.136B!0000!FAA7.C1C8.1DA5.E80D" or id eq "@!ADF2.014A.3A4E.E27B!0001!DC3E.136B!0000!D3A9.9D55.2985.E2C9" or id eq "@!ADF2.014A.3A4E.E27B!0001!DC3E.136B!0000!68DB.88F2.0B17.65C8"
16:04:14 INFO  GroupAssignUserTest.java:116 - Verifying groups and users consistency...
16:04:14 INFO  GroupAssignUserTest.java:143 - Attempting to modify group membership using /Users endpoint...
16:04:15 INFO  GroupAssignUserTest.java:163 - Removing one and adding one member...
16:04:15 INFO  GroupAssignUserTest.java:172 - Group has correct members
16:04:15 INFO  GroupAssignUserTest.java:186 - Users have correct memberships
16:04:15 INFO  GroupAssignUserTest.java:199 - Group '3 best demented buddies' removed
16:04:16 INFO  GroupAssignUserTest.java:199 - Group 'Auxiliary asylum' removed
16:04:16 INFO  GroupAssignUserTest.java:214 - User 'test-0.20407225425898645' removed
16:04:16 INFO  GroupAssignUserTest.java:214 - User 'test-0.021456855056185442' removed
16:04:16 INFO  GroupAssignUserTest.java:214 - User 'test-0.8250346392857232' removed
16:04:16 DEBUG QueryParamRetrievalTest.java:34 - Retrieving test users...
16:04:16 DEBUG QueryParamCreateUpdateTest.java:38 - Creating user from json...
16:04:19 DEBUG PatchReplaceUserTest.java:39 - Creating user from json...
16:04:19 DEBUG PatchAddUserTest.java:30 - Creating user from json...
16:04:20 DEBUG UserBaseTest.java:26 - User created with id @!ADF2.014A.3A4E.E27B!0001!DC3E.136B!0000!D041.940D.B9C7.EA13
16:04:20 DEBUG UserBaseTest.java:33 - Deleting user scim_test_bjensen_1
16:04:20 DEBUG UserBaseTest.java:36 - deleted
16:04:20 DEBUG PatchDeleteUserTest.java:30 - Creating user from json...
16:04:20 DEBUG PatchUserExtTest.java:40 - Creating user from json...
16:04:22 DEBUG PatchValueFilterUserTest.java:41 - User created with id @!ADF2.014A.3A4E.E27B!0001!DC3E.136B!0000!3F4F.BE23.F3E7.4BB5
16:04:22 DEBUG UserBaseTest.java:33 - Deleting user 1550009061446
16:04:22 DEBUG UserBaseTest.java:36 - deleted
16:04:22 DEBUG PatchGroupTest.java:47 - Creating group from json...
16:04:23 INFO  UsersBulkTest.java:35 - Sending a bulk with POST, PUT, and PATCH operations...
16:04:23 INFO  UsersBulkTest.java:49 - User id is @!ADF2.014A.3A4E.E27B!0001!DC3E.136B!0000!8AE5.8A08.2292.F1E6
16:04:23 INFO  UsersBulkTest.java:56 - Sending a bulk with one DELETE...
16:04:24 INFO  UsersBulkTest.java:80 - Sending a bulk with POSTs and DELETEs operations...
16:04:24 INFO  GroupsBulkTest.java:40 - Creating one user and one group using bulk json string
16:04:24 INFO  GroupsBulkTest.java:53 - User id is @!ADF2.014A.3A4E.E27B!0001!DC3E.136B!0000!89E0.8AEE.196A.8E5E
16:04:24 INFO  GroupsBulkTest.java:59 - Group id is @!ADF2.014A.3A4E.E27B!0001!DC3E.136B!0003!E3CA.1397
16:04:24 INFO  GroupsBulkTest.java:66 - Sending a bulk with a patch to insert admin user into group
16:04:25 INFO  GroupsBulkTest.java:98 - Cleaning...
16:04:32 DEBUG WrongPayloadUserTest.java:49 - Creating mimimal user from json...
16:04:33 DEBUG UserBaseTest.java:26 - User created with id @!ADF2.014A.3A4E.E27B!0001!DC3E.136B!0000!A485.6935.2035.DBEC
16:04:33 DEBUG UserBaseTest.java:33 - Deleting user scim_test_bjensen_1
16:04:34 DEBUG UserBaseTest.java:36 - deleted
16:04:34 INFO  AbstractScimClient.java:126 - Closing RestEasy client
Tests run: 109, Failures: 19, Errors: 0, Skipped: 22, Time elapsed: 33.372 sec <<< FAILURE!
inspectUserExtensionSchema(gluu.scim2.client.servicemeta.SchemasTest)  Time elapsed: 0.008 sec  <<< FAILURE!
java.lang.NullPointerException
        at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
        at gluu.scim2.client.servicemeta.SchemasTest.inspectUserExtensionSchema(SchemasTest.java:96)

createFull(gluu.scim2.client.singleresource.FullUserTest)  Time elapsed: 0.184 sec  <<< FAILURE!
java.lang.AssertionError: expected [201] but found [400]
        at org.testng.Assert.fail(Assert.java:93)
        at org.testng.Assert.failNotEquals(Assert.java:512)
        at org.testng.Assert.assertEqualsImpl(Assert.java:134)
        at org.testng.Assert.assertEquals(Assert.java:115)
        at org.testng.Assert.assertEquals(Assert.java:388)
        at org.testng.Assert.assertEquals(Assert.java:398)
        at gluu.scim2.client.UserBaseTest.createUserFromJson(UserBaseTest.java:22)
        at gluu.scim2.client.singleresource.FullUserTest.createFull(FullUserTest.java:36)

delete(gluu.scim2.client.singleresource.FullUserTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.NullPointerException
        at gluu.scim2.client.UserBaseTest.deleteUser(UserBaseTest.java:33)
        at gluu.scim2.client.singleresource.FullUserTest.delete(FullUserTest.java:105)

search1(gluu.scim2.client.search.PaginationUserSearchTest)  Time elapsed: 0.163 sec  <<< FAILURE!
java.lang.NullPointerException
        at gluu.scim2.client.search.PaginationUserSearchTest.search1(PaginationUserSearchTest.java:45)

searchNoMatches(gluu.scim2.client.search.SimpleSearchUserTest)  Time elapsed: 0.204 sec  <<< FAILURE!
java.lang.AssertionError: expected [200] but found [400]
        at org.testng.Assert.fail(Assert.java:93)
        at org.testng.Assert.failNotEquals(Assert.java:512)
        at org.testng.Assert.assertEqualsImpl(Assert.java:134)
        at org.testng.Assert.assertEquals(Assert.java:115)
        at org.testng.Assert.assertEquals(Assert.java:388)
        at org.testng.Assert.assertEquals(Assert.java:398)
        at gluu.scim2.client.search.SimpleSearchUserTest.searchNoMatches(SimpleSearchUserTest.java:132)

multipleRetrieval(gluu.scim2.client.singleresource.QueryParamRetrievalTest)  Time elapsed: 0.183 sec  <<< FAILURE!
java.lang.NullPointerException
        at gluu.scim2.client.singleresource.QueryParamRetrievalTest.multipleRetrieval(QueryParamRetrievalTest.java:41)

create1(gluu.scim2.client.singleresource.QueryParamCreateUpdateTest)  Time elapsed: 0.168 sec  <<< FAILURE!
java.lang.AssertionError: expected [201] but found [400]
        at org.testng.Assert.fail(Assert.java:93)
        at org.testng.Assert.failNotEquals(Assert.java:512)
        at org.testng.Assert.assertEqualsImpl(Assert.java:134)
        at org.testng.Assert.assertEquals(Assert.java:115)
        at org.testng.Assert.assertEquals(Assert.java:388)
        at org.testng.Assert.assertEquals(Assert.java:398)
        at gluu.scim2.client.singleresource.QueryParamCreateUpdateTest.create1(QueryParamCreateUpdateTest.java:44)

delete1(gluu.scim2.client.singleresource.QueryParamCreateUpdateTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.NullPointerException
        at gluu.scim2.client.UserBaseTest.deleteUser(UserBaseTest.java:33)
        at gluu.scim2.client.singleresource.QueryParamCreateUpdateTest.delete1(QueryParamCreateUpdateTest.java:53)

delete(gluu.scim2.client.singleresource.QueryParamCreateUpdateTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.NullPointerException
        at gluu.scim2.client.UserBaseTest.deleteUser(UserBaseTest.java:33)
        at gluu.scim2.client.singleresource.QueryParamCreateUpdateTest.delete(QueryParamCreateUpdateTest.java:149)

createForReplace(gluu.scim2.client.patch.PatchReplaceUserTest)  Time elapsed: 0.165 sec  <<< FAILURE!
java.lang.AssertionError: expected [201] but found [400]
        at org.testng.Assert.fail(Assert.java:93)
        at org.testng.Assert.failNotEquals(Assert.java:512)
        at org.testng.Assert.assertEqualsImpl(Assert.java:134)
        at org.testng.Assert.assertEquals(Assert.java:115)
        at org.testng.Assert.assertEquals(Assert.java:388)
        at org.testng.Assert.assertEquals(Assert.java:398)
        at gluu.scim2.client.UserBaseTest.createUserFromJson(UserBaseTest.java:22)
        at gluu.scim2.client.patch.PatchReplaceUserTest.createForReplace(PatchReplaceUserTest.java:40)

delete(gluu.scim2.client.patch.PatchReplaceUserTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.NullPointerException
        at gluu.scim2.client.UserBaseTest.deleteUser(UserBaseTest.java:33)
        at gluu.scim2.client.patch.PatchReplaceUserTest.delete(PatchReplaceUserTest.java:198)

createForDel(gluu.scim2.client.patch.PatchDeleteUserTest)  Time elapsed: 0.207 sec  <<< FAILURE!
java.lang.AssertionError: expected [201] but found [400]
        at org.testng.Assert.fail(Assert.java:93)
        at org.testng.Assert.failNotEquals(Assert.java:512)
        at org.testng.Assert.assertEqualsImpl(Assert.java:134)
        at org.testng.Assert.assertEquals(Assert.java:115)
        at org.testng.Assert.assertEquals(Assert.java:388)
        at org.testng.Assert.assertEquals(Assert.java:398)
        at gluu.scim2.client.UserBaseTest.createUserFromJson(UserBaseTest.java:22)
        at gluu.scim2.client.patch.PatchDeleteUserTest.createForDel(PatchDeleteUserTest.java:31)

delete(gluu.scim2.client.patch.PatchDeleteUserTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.NullPointerException
        at gluu.scim2.client.UserBaseTest.deleteUser(UserBaseTest.java:33)
        at gluu.scim2.client.patch.PatchDeleteUserTest.delete(PatchDeleteUserTest.java:53)

create(gluu.scim2.client.patch.PatchUserExtTest)  Time elapsed: 0.726 sec  <<< FAILURE!
java.lang.AssertionError: expected [201] but found [400]
        at org.testng.Assert.fail(Assert.java:93)
        at org.testng.Assert.failNotEquals(Assert.java:512)
        at org.testng.Assert.assertEqualsImpl(Assert.java:134)
        at org.testng.Assert.assertEquals(Assert.java:115)
        at org.testng.Assert.assertEquals(Assert.java:388)
        at org.testng.Assert.assertEquals(Assert.java:398)
        at gluu.scim2.client.UserBaseTest.createUserFromJson(UserBaseTest.java:22)
        at gluu.scim2.client.patch.PatchUserExtTest.create(PatchUserExtTest.java:41)

delete(gluu.scim2.client.patch.PatchUserExtTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.NullPointerException
        at gluu.scim2.client.UserBaseTest.deleteUser(UserBaseTest.java:33)
        at gluu.scim2.client.patch.PatchUserExtTest.delete(PatchUserExtTest.java:105)

patch2(gluu.scim2.client.patch.PatchGroupTest)  Time elapsed: 0.21 sec  <<< FAILURE!
java.lang.NullPointerException
        at gluu.scim2.client.patch.PatchGroupTest.getTestUsers(PatchGroupTest.java:161)
        at gluu.scim2.client.patch.PatchGroupTest.patch2(PatchGroupTest.java:72)

containabilityAll(gluu.scim2.client.corner.SpecialCharsTest)  Time elapsed: 0.189 sec  <<< FAILURE!
java.lang.NullPointerException
        at gluu.scim2.client.corner.SpecialCharsTest.containabilityAll(SpecialCharsTest.java:72)

containabilityAllInGivenName(gluu.scim2.client.corner.SpecialCharsTest)  Time elapsed: 0.209 sec  <<< FAILURE!
java.lang.NullPointerException
        at gluu.scim2.client.corner.SpecialCharsTest.containabilityAllInGivenName(SpecialCharsTest.java:93)

containabilityAny(gluu.scim2.client.corner.SpecialCharsTest)  Time elapsed: 0.203 sec  <<< FAILURE!
java.lang.NullPointerException
        at gluu.scim2.client.corner.SpecialCharsTest.containabilityAny(SpecialCharsTest.java:49)


Results :

Failed tests:   inspectUserExtensionSchema(gluu.scim2.client.servicemeta.SchemasTest)
  createFull(gluu.scim2.client.singleresource.FullUserTest): expected [201] but found [400]
  delete(gluu.scim2.client.singleresource.FullUserTest)
  search1(gluu.scim2.client.search.PaginationUserSearchTest)
  searchNoMatches(gluu.scim2.client.search.SimpleSearchUserTest): expected [200] but found [400]
  multipleRetrieval(gluu.scim2.client.singleresource.QueryParamRetrievalTest)
  create1(gluu.scim2.client.singleresource.QueryParamCreateUpdateTest): expected [201] but found [400]
  delete1(gluu.scim2.client.singleresource.QueryParamCreateUpdateTest)
  delete(gluu.scim2.client.singleresource.QueryParamCreateUpdateTest)
  createForReplace(gluu.scim2.client.patch.PatchReplaceUserTest): expected [201] but found [400]
  delete(gluu.scim2.client.patch.PatchReplaceUserTest)
  createForDel(gluu.scim2.client.patch.PatchDeleteUserTest): expected [201] but found [400]
  delete(gluu.scim2.client.patch.PatchDeleteUserTest)
  create(gluu.scim2.client.patch.PatchUserExtTest): expected [201] but found [400]
  delete(gluu.scim2.client.patch.PatchUserExtTest)
  patch2(gluu.scim2.client.patch.PatchGroupTest)
  containabilityAll(gluu.scim2.client.corner.SpecialCharsTest)
  containabilityAllInGivenName(gluu.scim2.client.corner.SpecialCharsTest)
  containabilityAny(gluu.scim2.client.corner.SpecialCharsTest)

Tests run: 109, Failures: 19, Errors: 0, Skipped: 22

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  37.070 s
[INFO] Finished at: 2019-02-12T16:04:34-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project scim-client2: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/yamildiazaguirre/Documents/SCIM-Client/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

## Configuration and Log files

Config-scim-test.properties

```properties
test.server.name=https://myservercarnales.com
#For test-mode only:
test.auth_server_oidc_url=https://myservercarnales.com/oxauth/.well-known/openid-configuration

umaAatClientId=@!ADF2.014A.3A4E.E27B!0001!DC3E.136B!0008!0F39.6D2C
umaAatClientJksPath=profiles/scim-rp.jks
umaAatClientJksPassword=secret
umaAatClientKeyId=

```

Thank you,

Yamil Díaz

**Comment by willow9886** [comment]
Have you opened a ticket on support? We only do issue resolution there. If it's determined to be a big, we will open on GitHub and resolve as needed. The support app keeps things centralized, organized, and more accessible for other users facing similar issues.
